# CVE-2013-7267, CVE-2019-17054, CVE-2025-38666
blacklist appletalk
install appletalk /bin/false

# CVE-2019-17052, CVE-2022-1204
blacklist ax25
install ax25 /bin/false

# CVE-2026-64096, CVE-2026-80600, CVE-2026-72233
blacklist batman-adv
install batman-adv /bin/false

# CVE-2026-43456
blacklist bonding
install bonding /bin/false

# CVE-2023-1829
blacklist cls_tcindex
install cls_tcindex /bin/false

# CVE-2017-6074
blacklist dccp
install dccp /bin/false

# CVE-2026-43284, CVE-2026-46300 (Dirty Frag / Fragnesia)
blacklist esp4
install esp4 /bin/false

# CVE-2026-43284 (Dirty Frag)
blacklist esp6
install esp6 /bin/false

# No CVE found
blacklist l2tp_eth
install l2tp_eth /bin/false

# CVE-2026-80996
blacklist l2tp_netlink
install l2tp_netlink /bin/false

# CVE-2026-53262
blacklist l2tp_ppp
install l2tp_ppp /bin/false

# CVE-2026-23098
blacklist netrom
install netrom /bin/false

# CVE-2019-14615, CVE-2019-15215
blacklist prism54
install prism54 /bin/false

# CVE-2026-43502, CVE-2026-43494 (ZcopyReaper / PinTheft)
blacklist rds
install rds /bin/false

# CVE-2026-43502, CVE-2026-43494 (ZcopyReaper / PinTheft)
blacklist rds_tcp
install rds_tcp /bin/false

# CVE-2026-80814
blacklist rndis_host
install rndis_host /bin/false

# CVE-2026-23460
blacklist rose
install rose /bin/false

# CVE-2026-43500 (Dirty Frag)
blacklist rxrpc
install rxrpc /bin/false

# CVE-2026-64564 (SCTPhantom)
blacklist sctp
install sctp /bin/false

# CVE-2026-43411, CVE-2026-64543, CVE-2026-74490, CVE-2026-52993
blacklist tipc
install tipc /bin/false

# CVE-2022-25375
blacklist usb_f_rndis
install usb_f_rndis /bin/false
