# All these filesystems are blacklisted on openSUSE Tumbleweed

blacklist adfs
install adfs /bin/false

blacklist affs
install affs /bin/false

blacklist befs
install befs /bin/false

blacklist bfs
install bfs /bin/false

blacklist cramfs
install cramfs /bin/false

blacklist efs
install efs /bin/false

blacklist exofs
install exofs /bin/false

blacklist f2fs
install f2fs /bin/false

blacklist freevxfs
install freevxfs /bin/false

blacklist hfs
install hfs /bin/false

blacklist hfsplus
install hfsplus /bin/false

blacklist hpfs
install hpfs /bin/false

blacklist jffs2
install jffs2 /bin/false

blacklist jfs
install jfs /bin/false

blacklist kafs
install kafs /bin/false

blacklist minix
install minix /bin/false

blacklist nilfs2
install nilfs2 /bin/false

blacklist ntfs
install ntfs /bin/false

blacklist ntfs3
install ntfs3 /bin/false

blacklist omfs
install omfs /bin/false

blacklist orangefs
install orangefs /bin/false

blacklist pstore
install pstore /bin/false

blacklist qnx4
install qnx4 /bin/false

blacklist qnx6
install qnx6 /bin/false

blacklist reiserfs
install reiserfs /bin/false

blacklist romfs
install romfs /bin/false

blacklist sysv
install sysv /bin/false

blacklist ufs
install ufs /bin/false

blacklist zonefs
install zonefs /bin/false

