
# See https://a13xp0p0v.github.io/2017/03/24/CVE-2017-2636.html
dev.tty.ldisc_autoload = 0

# See https://docs.kernel.org/admin-guide/sysctl/fs.html#protected-fifos
fs.protected_fifos = 2
# See https://docs.kernel.org/admin-guide/sysctl/fs.html#protected-hardlinks
fs.protected_hardlinks = 1
# See https://docs.kernel.org/admin-guide/sysctl/fs.html#protected-regular
fs.protected_regular = 2
# See https://docs.kernel.org/admin-guide/sysctl/fs.html#protected-symlinks
fs.protected_symlinks = 1

# See https://docs.kernel.org/admin-guide/sysctl/fs.html#suid-dumpable
fs.suid_dumpable = 0

# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#dmesg-restrict
kernel.dmesg_restrict = 1

# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#io-uring-disabled
-kernel.io_uring_disabled = 2
# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#io-uring-group
#-kernel.io_uring_group = 0

# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#kexec-load-disabled
-kernel.kexec_load_disabled = 1

# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#kptr-restrict
kernel.kptr_restrict = 2

# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#modules-disabled
#kernel.modules_disabled = 1

# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#perf-event-paranoid
kernel.perf_event_paranoid = 2

# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#randomize-va-space
kernel.randomize_va_space = 2

# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#shm-rmid-forced
kernel.shm_rmid_forced = 1

# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#sysrq
# 176 = 128 + 32 + 16
kernel.sysrq = 176

# See https://docs.kernel.org/admin-guide/sysctl/kernel.html#unprivileged-bpf-disabled
-kernel.unprivileged_bpf_disabled = 2

# See https://www.kernel.org/doc/Documentation/security/Yama.txt
-kernel.yama.ptrace_scope = 2

# See https://docs.kernel.org/admin-guide/sysctl/net.html#bpf-jit-harden
-net.core.bpf_jit_harden = 2
# See https://docs.kernel.org/admin-guide/sysctl/net.html#bpf-jit-kallsyms
-net.core.bpf_jit_kallsyms = 0

# XXX May break Chrome sandbox and rootless containers
# user.max_user_namespaces = 0

# See https://docs.kernel.org/admin-guide/sysctl/vm.html#mmap-rnd-bits
-vm.mmap_rnd_bits = 32
# See https://docs.kernel.org/admin-guide/sysctl/vm.html#mmap-rnd-compat-bits
-vm.mmap_rnd_compat_bits = 16

# See https://docs.kernel.org/admin-guide/sysctl/vm.html#unprivileged-userfaultfd
-vm.unprivileged_userfaultfd = 0
