---
- name: Copy dbus files
  copy:
    src: "dbus/{{ item }}"
    dest: "/etc/dbus-1/session.d/{{ item }}"
    owner: root
    group: root
    mode: "0600"
  loop:
    # https://linnemanlabs.com/posts/hello-my-name-is-orca/
    # TODO notify:
    # busctl --user call org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus ReloadConfig
    - block-orca-impersonation.conf
