---
- name: Create /etc/sudoers.d
  shell: mkdir -m 750 -p /etc/sudoers.d
  args:
    creates: /etc/sudoers.d

- name: Add custom sudo configuration
  copy:
    src: sudoers.d/custom
    dest: /etc/sudoers.d/custom
    owner: root
    group: root
    mode: 0600
