---
- name: Copy sysctl files
  copy:
    src: "sysctl.d/{{ item }}"
    dest: "/etc/sysctl.d/{{ item }}"
    owner: root
    group: root
    mode: "0600"
  loop:
    - 99-hardening.conf
    - 99-net.conf
